name: build

on:
  push:
    branches: [ "develop" ]
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@main
    with:
      solution-file-path: ${{ vars.SOLUTION_FILE_PATH }}
      artifacts: ${{ vars.BUILD_ARTIFACTS }}
